#!/bin/bash

if [[ $USER != 'root' ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

MYIP=$(wget -qO- ipv4.icanhazip.com)

#vps="zvur";
vps="aneka";

if [[ $vps = "zvur" ]]; then
	source="http://scripts.gapaiasa.com"
else
	source="http://anekascript.anekavps.us"
fi

# go to root
cd

disable-user-expire
clear

echo "---------------------------- DAFTAR AKUN SSH EXPIRE ----------------------------"

if [[ $vps = "zvur" ]]; then
	echo "            ALL SUPPORTED BY Net.Store ID            "
	echo "           https://www.facebook.com/cybernet.darknet/           "
else
	echo "            ALL SUPPORTED BY Net.Store ID            "
	echo "           https://www.facebook.com/cybernet.darknet/           "
fi

	echo "       DEVELOPED BY Net.Store ID        "
echo ""

cat /root/expireduser.txt
echo ""

cd ~/
rm -f /root/IP
